function [obs_lat, obs_lon, obs_elev] = read_obs_locations_from_profile(profile_path, npoint)
% READ_OBS_LOCATIONS_FROM_PROFILE  parse the NR truth prof.dat and return the
% observation locations in the exact order they appear in the file
%
%   The NR profile is generated by wrf_rttov_d01_75km_les.m. Each observation
%   block contains a marker line
%       ! Elevation (km), latitude and longitude (degrees)
%   immediately followed by one data line with three numbers:
%       elevation (km)   latitude (deg)   longitude (deg)
%
%   Input:
%       profile_path : full path to the NR truth prof.dat
%       npoint       : expected number of observation locations (676)
%   Output:
%       obs_lat, obs_lon, obs_elev : column vectors (npoint x 1), in the same
%                                    order as they appear in the profile
%
%   The marker is searched line by line (no fixed line numbers assumed). Any
%   anomaly (unreadable file, marker without data, non-finite or invalid
%   values, wrong observation count) raises error() with the full profile
%   path and the reason; bad records are never silently skipped.

marker = '! Elevation (km), latitude and longitude (degrees)';

fid = fopen(profile_path, 'r');
if fid < 0
    error('Cannot open NR truth profile ''%s'' for reading (npoint=%d).', ...
          profile_path, npoint);
end
cleanup = onCleanup(@() fclose(fid));

obs_lat  = zeros(0, 1);
obs_lon  = zeros(0, 1);
obs_elev = zeros(0, 1);
nline = 0;
while true
    line = fgetl(fid);
    if ~ischar(line)
        break; % end of file
    end
    nline = nline + 1;
    if ~isempty(strfind(line, marker))
        data_line = fgetl(fid);
        if ~ischar(data_line)
            error('NR truth profile ''%s'': location marker at line %d is followed by end of file, no observation data.', ...
                  profile_path, nline);
        end
        vals = sscanf(data_line, '%f');
        if numel(vals) < 3
            error('NR truth profile ''%s'': line %d after the location marker does not contain elevation, latitude and longitude: ''%s''', ...
                  profile_path, nline + 1, data_line);
        end
        obs_elev(end+1, 1) = vals(1);
        obs_lat(end+1, 1)  = vals(2);
        obs_lon(end+1, 1)  = vals(3);
    end
end

if isempty(obs_lat)
    error('NR truth profile ''%s'': no location marker ''%s'' found, cannot recover any observation location.', ...
          profile_path, marker);
end
if isempty(npoint) || numel(obs_lat) ~= npoint
    error('NR truth profile ''%s'': found %d observation locations but npoint=%d; the profile is incomplete or inconsistent with the experiment setting.', ...
          profile_path, numel(obs_lat), npoint);
end

% validity: finite values and physically plausible ranges
bad = ~isfinite(obs_lat) | ~isfinite(obs_lon) | ~isfinite(obs_elev) | ...
      obs_lat < -90 | obs_lat > 90 | ...
      obs_lon < -360 | obs_lon > 360 | ...
      obs_elev < -1 | obs_elev > 20; % km; WRF terrain heights are ~0-3 km here
if any(bad)
    idx = find(bad, 1);
    error('NR truth profile ''%s'': observation %d has invalid elevation/latitude/longitude: elev=%.4f km, lat=%.6f deg, lon=%.6f deg.', ...
          profile_path, idx, obs_elev(idx), obs_lat(idx), obs_lon(idx));
end

end
