#!/bin/sh
# This script is designed to run a series of WRF (Weather Research and Forecasting) model integrations.
# It functions as a "cold-start" cycling forecast system.
#
# CRITICAL FEATURE: To prevent model instability ("blow-ups"), this script uses a unified
# safety mechanism for ALL forecast cycles:
#   1. It copies a stable "base" wrfinput file for the current cycle (generated by real.exe).
#   2. It links to the output from the previous forecast step (a special file for the first
#      cycle, or the script's own output for subsequent cycles).
#   3. It runs a helper script to update the base file with the state from the previous step.

#==========================================================
# 1. JOB SCHEDULER CONFIGURATION
#==========================================================
#BSUB -J WRF_CTRL
#BSUB -q fat_384
#BSUB -n 160
#BSUB -oo forecast_stable.out
#BSUB -eo forecast_stable.err

#==========================================================
# 2. USER-CONFIGURABLE PARAMETERS
#==========================================================

# --- Core Paths ---
export BASE_DIR=/share/home/lililei1/kcfu/tc_mangkhut
export WRF_EM_REAL_DIR=/share/home/lililei1/kcfu/models/real_WRF_WPS/V4.1/WRF-4.1/test/em_real
export ICBC_DIR=${BASE_DIR}/1icbc
export FORECAST_BASE_DIR=${BASE_DIR}/6forecast_only_stable
export HELPER_SCRIPT_DIR=${BASE_DIR}/0necessay_files

# --- Time Control ---
export START_TIME="2018-09-10 00:00:00"
export END_TIME="2018-09-13 00:00:00"
export FORECAST_HOURS=6

# --- WRF & Ensemble Configuration ---
export NUM_MEMBERS=50
export MEMBER_ID_MAP=(0 $(seq 1 29) 31 32 36 38 39 40 41 42 43 45 47 48 49 50 51 54 62 69 70 71 73)
export MAX_DOM=1
export MPI_COMMAND="mpirun"

# --- Retry Logic for WRF Execution ---
export MAX_ATTEMPTS=3
export MIN_WrfOUT_SIZE_BYTES=1000000 # 1 MB

#==========================================================
# 3. SCRIPT SETUP (No user changes needed below this line)
#==========================================================
#set -e
start_ts=$(date +%s -d "$START_TIME")
end_ts=$(date +%s -d "$END_TIME")
interval_seconds=$((FORECAST_HOURS * 3600))
mkdir -p ${FORECAST_BASE_DIR}/output
mkdir -p ${FORECAST_BASE_DIR}/run_wrf
echo "Forecast output will be saved in: ${FORECAST_BASE_DIR}/output"

#==========================================================
# 4. MAIN FORECASTING CYCLE
#==========================================================
echo "Starting WRF forecast cycles with a unified stability mechanism..."
current_ts=$start_ts
while [ "$current_ts" -le "$end_ts" ]; do

    # --- 4.1. Calculate cycle times ---
    current_year=$(date -d "@$current_ts" "+%Y"); current_month=$(date -d "@$current_ts" "+%m"); current_day=$(date -d "@$current_ts" "+%d"); current_hour=$(date -d "@$current_ts" "+%H"); current_min=$(date -d "@$current_ts" "+%M")
    current_time_str_fs="${current_day}_${current_hour}_${current_min}"
    current_time_str_wrf="${current_year}-${current_month}-${current_day}_${current_hour}:${current_min}:00"

    next_ts=$((current_ts + interval_seconds))
    next_year=$(date -d "@$next_ts" "+%Y"); next_month=$(date -d "@$next_ts" "+%m"); next_day=$(date -d "@$next_ts" "+%d"); next_hour=$(date -d "@$next_ts" "+%H"); next_min=$(date -d "@$next_ts" "+%M")
    next_time_str_wrf="${next_year}-${next_month}-${next_day}_${next_hour}:${next_min}:00"

    echo "Processing cycle starting at: $current_time_str_wrf"

    # --- 4.2. Loop through each ensemble member ---
    for ((imem=1; imem<=NUM_MEMBERS; imem++)); do
        mem_padded=$(printf "%03d" $imem)
        mem_from_map=$(printf "%03d" ${MEMBER_ID_MAP[$imem]})
        echo "--> Running Member: $mem_padded (maps to file ID $mem_from_map)"

        # --- 4.2.1. Setup member-specific run directory ---
        run_dir=${FORECAST_BASE_DIR}/run_wrf/${current_time_str_fs}/${mem_padded}
        output_dir=${FORECAST_BASE_DIR}/output/${current_time_str_fs}/${mem_padded}
        mkdir -p $run_dir; mkdir -p $output_dir; cd $run_dir
        ln -sf ${WRF_EM_REAL_DIR}/* .

        # --- 4.2.3. Prepare Initial and Boundary Conditions ---
        echo "    (Applying stability-preserving update)"

        # Determine the path to the previous state file (the source for the ncks update).
        previous_state_path=""
        if [ "$current_ts" -eq "$start_ts" ]; then
            # For the VERY FIRST cycle, use the special initial file from the 10_00_00 run.
            echo "    (First cycle: using initial state from .../10_00_00/firstguess.mem...)"
            previous_state_path="/share/home/lililei1/kcfu/tc_mangkhut/4assimilation/0mem_all_time/cyclingDA/10_00_00/firstguess.mem${mem_padded}"
        else
            # For all subsequent cycles, use the output from this script's previous cycle.
            previous_ts=$((current_ts - interval_seconds))
            prev_day=$(date -d "@$previous_ts" "+%d"); prev_hour=$(date -d "@$previous_ts" "+%H"); prev_min=$(date -d "@$previous_ts" "+%M")
            prev_time_str_fs="${prev_day}_${prev_hour}_${prev_min}"
            previous_state_path="${FORECAST_BASE_DIR}/output/${prev_time_str_fs}/${mem_padded}/wrfout_d01_${current_time_str_wrf}"
        fi

        if [ ! -f "$previous_state_path" ]; then
            echo "    ERROR: Source state file not found! Halting."
            echo "    Missing file: $previous_state_path"
            exit 1
        fi

        # THE UNIFIED CRITICAL SECTION (FOR ALL CYCLES)
        # 1. Copy the stable base wrfinput file (template for the current time step).
        cp "${ICBC_DIR}/IC/wrfinput_${current_year}${current_month}${current_day}${current_hour}_mem${mem_from_map}" ./wrfinput_d01
        # 2. Link the source state file.
        ln -sf "${previous_state_path}" ./previous_wrfout_d01
        # 3. Copy and run the helper script to merge them.
        cp "${HELPER_SCRIPT_DIR}/update_wrfinput_from_wrfout.sh" .
        ./update_wrfinput_from_wrfout.sh

        # Link boundary conditions.
        ln -sf "${ICBC_DIR}/wrfbdy_d01_mem${mem_from_map}" ./wrfbdy_d01

        # --- 4.2.4. Configure namelist.input (omitted for brevity, same as before) ---
        rm ./namelist.input
        cp ${BASE_DIR}/0necessay_files/namelist.wrf ./namelist.input
        sed -i "s#run_hours.*#run_hours = ${FORECAST_HOURS},#g" namelist.input
        sed -i "s#start_year.*#start_year = ${MAX_DOM}*${current_year},#g" namelist.input
        sed -i "s#start_month.*#start_month = ${MAX_DOM}*${current_month},#g" namelist.input
        sed -i "s#start_day.*#start_day = ${MAX_DOM}*${current_day},#g" namelist.input
        sed -i "s#start_hour.*#start_hour = ${MAX_DOM}*${current_hour},#g" namelist.input
        sed -i "s#start_minute.*#start_minute = ${MAX_DOM}*${current_min},#g" namelist.input
        sed -i "s#end_year.*#end_year = ${MAX_DOM}*${next_year},#g" namelist.input
        sed -i "s#end_month.*#end_month = ${MAX_DOM}*${next_month},#g" namelist.input
        sed -i "s#end_day.*#end_day = ${MAX_DOM}*${next_day},#g" namelist.input
        sed -i "s#end_hour.*#end_hour = ${MAX_DOM}*${next_hour},#g" namelist.input
        sed -i "s#end_minute.*#end_minute = ${MAX_DOM}*${next_min},#g" namelist.input

        # --- 4.2.5. Execute WRF with Retry Logic (omitted for brevity, same as before) ---
        TARGET_FILE="wrfout_d01_${next_time_str_wrf}"; success=false
        echo "    expecting ${TARGET_FILE}"
        for attempt_num in $(seq 1 $MAX_ATTEMPTS); do
            echo "    Starting WRF execution (Attempt $attempt_num/$MAX_ATTEMPTS)..."; rm -f wrfout_d01* rsl.*
            $MPI_COMMAND ./wrf.exe
            if [ -f "$TARGET_FILE" ]; then
                actual_size=$(stat -c%s "$TARGET_FILE"); if [ "$actual_size" -ge "$MIN_WrfOUT_SIZE_BYTES" ]; then
                    echo "    SUCCESS: WRF run completed."; success=true; break
                else echo "    FAILURE: Output file is too small ($actual_size bytes)."
                fi
            else echo "    FAILURE: Output file was not created."
            fi
            if [ "$attempt_num" -lt "$MAX_ATTEMPTS" ]; then echo "    Retrying in 5 seconds..."; sleep 5; fi
        done
        
        # --- 4.2.6. Finalize and Clean Up (omitted for brevity, same as before) ---
        if [ "$success" = true ]; then
            mv $TARGET_FILE $output_dir/; echo "    Output moved to: $output_dir/"
        else
            echo "    FATAL ERROR: All $MAX_ATTEMPTS attempts failed. Aborting script."; exit 1
        fi
        cd ${BASE_DIR}
    done
    current_ts=$next_ts
    echo "--------------------------------------------------"
done

echo "===================="
echo "All forecast cycles completed successfully."
echo "===================="
