#!/bin/sh

###BSUB -n 80

#BSUB -J wrf_ensemble[38-50]
#BSUB -n 144
#BSUB -eo test.err
#BSUB -oo test.out
#BSUB -R "span[ptile=24]"
#BSUB -q largemem

###BSUB -q fat_384

my_list=(0 $(seq 1 29) 31 32 36 38 39 40 41 42 43 45 47 48 49 50 51 54 62 69 70 71 73)
imem=${LSB_JOBINDEX}
mem_from80=$(printf "%03d" ${my_list[$imem]})
mem=$(printf "%03d" $imem)
cycle_run_wrf_dir=${base_dir}/5cyclingDA/run_wrf/${mem}
mkdir -p $cycle_run_wrf_dir
cd ${cycle_run_wrf_dir}
ln -sf /share/home/lililei1/kcfu/models/real_WRF_WPS/V4.1/WRF-4.1/test/em_real/* .
ln -sf ${base_dir}/1icbc/wrfbdy_d01_mem${mem_from80} ./wrfbdy_d01
ln -sf ${post_anal_dir}/analysis.mem${mem} ./post_assim
rm namelist.input
cp ${base_dir}/0necessay_files/namelist.wrf ./namelist.input
sed -i "s#run_hours.*#run_hours = ${cycle_interval},#g" namelist.input
sed -i "s#start_day.*#start_day = ${max_dom}*${current_day},#g" namelist.input
sed -i "s#start_hour.*#start_hour = ${max_dom}*${current_hour},#g" namelist.input
sed -i "s#start_minute.*#start_minute = ${max_dom}*${current_min},#g" namelist.input
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#in case of booming of ocean fileds, assign analysis into wrfinput generated by real.exe

cp ${base_dir}/1icbc/IC/wrfinput_201809${current_day}${current_hour}_mem${mem_from80} ./wrfinput_d01
cp ${base_dir}/0necessay_files/ncks_AssignPostaasim2Wrfinput.sh .
./ncks_AssignPostaasim2Wrfinput.sh

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
mkdir -p ${base_dir}/4assimilation/0mem_all_time/cyclingDA/${next_time}/ #make sure next time fcst is moved to here
echo "wrf running mem${mem} at ${current_time}"
mpirun ./wrf.exe

cycle_wrfout_dir=${base_dir}/4assimilation/0mem_all_time/cyclingDA/${next_time} #now move wrfout to next time
mv wrfout_d01_2018-09-${next_day}_${next_hour}:${next_min}:00 ${cycle_wrfout_dir}/firstguess.mem${mem}
rm wrfout*
rm wrfrst*